DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS playlists_tracks;
DROP TABLE IF EXISTS tracks_artists;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS playlists;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";
